import { Inter } from 'next/font/google'
import './globals.css'
import GlobalContextProvider from '@/state/context/GlobalContext'
import { Toaster } from 'react-hot-toast'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`{inter.className} w-screen flex flex-col`}>
        <GlobalContextProvider>
          <Toaster />
          {children}
        </GlobalContextProvider>
      </body>
    </html>
  )
}
